server:
  port: ${PORT:50012}
  servlet:
    context-path: /
spring:
  application:
    name: service-push
  redis:
    host: 192.168.1.200
    port: 6379
    database: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.1.200:50100/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

